# Generated by Django 2.2 on 2019-04-22 14:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190420_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='excerpt',
            field=ckeditor.fields.RichTextField(default='null'),
        ),
        migrations.AddField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
