# Generated by Django 2.2 on 2019-04-23 01:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190422_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='excerpt',
            field=ckeditor.fields.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='feature_img',
            field=models.ImageField(blank=True, upload_to='feature_pics'),
        ),
    ]
